def abbr_sub(tokens):        #l is a list of tokens
    for token in tokens:
      if token in abbr_dict:
        current_token = tokens.index(token)
        tokens = tokens[:current_token] + abbr_dict[token] + tokens[current_token + 1:]
    return(tokens)


# A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
abbr_dict={
    'ack': ['acknowlegdgment'],
    'afg': ['afghanistan'],
    'afk': ['away', 'from', 'keyboard'],
    'aka': ['also', 'known', 'as'],
    'ama': ['ask', 'me', 'anything'],
    'app': ['application'],
    'alap': ['as', 'late', 'as', 'possible'],    
    'asap': ['as', 'soon', 'as', 'possible'],
    'atb': ['all', 'the', 'best'],
    'au': ['australia'],
    'b&': ['banned'],
    'b4': ['before'],
    'bae': ['before', 'anyone', 'else'],
    'bc': ['because'],
    'bday': ['birthday'],
    'b-day': ['birthday'],
    'bf': ['boyfriend'],
    'bff': ['best', 'friend', 'forever'],
    'bg': ['background'],
    'bif': ['before', 'i', 'forget'],
    'bol': ['best', 'of', 'luck'],
    'br': ['brazil'],
    'brb': ['be', 'right', 'back'],
    'btt': ['back', 'to', 'topic'],
    'btw': ['by', 'the', 'way'],
    'c': ['see'],
    'ca': ['canada'],
    'cam': ['camera'],
    'cc': ['carbon', 'copy'],
    'cd': ['compact','disk'],
    'clg': ['college'],
    'cm': ['call', 'me'],
    'cn': ['china'],
    'col': ['call'],
    'cpy': ['copy'],
    'cr8': ['create'],
    'cre8': ['create'],
    'coz': ['because'],
    'cos': ['because'],
    'cu': ['see', 'you'],
    'cuz': ['because'],
    'cwyl': ['chat', 'with', 'you', 'later'],
    'cya': ['see', 'you'],
    'da': ['the'],
    'dat': ['that'],
    'der': ['there'],
    'diy': ['do', 'it', 'yourself'],
    'dk': ["don't", 'know'],
    'dl': ['download'],
    'd/l': ['download'],
    'dm': ['direct', 'message'],
    'dn': ['down'],
    'dnt': ["don't"],
    'dunno': ["don't", 'know'],
    'dupe': ['duplicate'],
    'eg.': ['example', 'given'],
    'eol': ['end', 'of', 'life'],
    'eos': ['end', 'of', 'show'],
    'eot': ['end', 'of', 'transmission'],
    'eva': ['ever'],
    'every1' : ['everyone'],
    'fab': ['fabulous'],
    'faq': ['frequently', 'asked', 'questions'],
    'fb': ['facebook'],
    'fc': ['fingers', 'crossed'],
    'fomo': ['fear', 'of', 'missing', 'out'],
    'fr': ['france'],
    'frnd': ['friend'],
    'frnds': ['friends'],
    'ga': ['good', 'afternoon'],
    'gal': ['get', 'a', 'life'],
    'gd': ['group', 'discussion'],
    'ge': ['good', 'evening'],
    'gf': ['girl', 'friend'],
    'gfu': ['good', 'for', 'you'],
    'gg': ['good', 'good'],
    'gm': ['good', 'morning'],
    'gtg': ['got', 'to', 'go'],
    'g2g': ['got', 'to', 'go'],
    'gj': ['good', 'job'],
    'gl': ['good', 'luck'],
    'gnight': ['good', 'night'],
    'gn8': ['good', 'night'],
    'gn': ['good', 'night'],
    'goi': ['get', 'over', 'it'],
    'grt': ['great'],
    'gr8': ['great'],
    'gud': ['good'],
    'h8': ['hate'],
    'hbd': ['happy', 'birthday'],
    'hbday': ['happy', 'birthday'],
    'h-bday': ['happy', 'birthday'],
    'hp': ['health', 'point'],
    'hr': ['human', 'resources'],
    'hw': ['home', 'work'],
    'i2': ['i', 'too'],
    'ib': ['i', 'am', 'back'],
    'ic': ['i', 'see'],
    'icymi': ['in', 'case', 'you', 'missed', 'it'],
    'idbi': ['i', "don't", 'believe', 'it'],
    'id': ['identity', 'document'],
    'idc': ['i', "don't", 'care'],
    'idunno': ['i', "don't", 'know'],
    'idk': ['i', "don't", 'know'],
    'ie': ['ireland'],
    'iir': ['if', 'i', 'remember'],
    'ig': ['i', 'guess'],
    'ik': ['i', 'know'],
    'ikr': ['i', 'know', 'right'],
    'il': ['israel'],
    'ily': ['i', 'love', 'you'],
    'ilysm': ['i', 'love', 'you', 'so', 'much'],
    'im': ['instant', 'message'],
    'imo': ['in', 'my', 'opinion'],
    'imp': ['important'],
    'ims': ['i', 'am', 'sorry'],
    'ind': ['india'],
    'irl': ['in', ' real', 'life'],
    'irmc': ['i', 'rest', 'my', 'case'],
    'ity': ['italy'],
    'itt': ['in', 'this', 'thread'],
    'iykwim': ['if', 'you', 'know', 'what', 'i', 'mean'],
    'iyo': ['in', 'your', 'opinion'],
    'jam': ['just', 'a', 'minute'],
    'jj': ['just', 'joking'],
    'jk': ['just', 'kidding'],
    'jp': ['japan'],
    'jt': ['just', 'teasing'],
    'jv': ['joint', 'venture'],
    'k': ['okay'],
    'kk': ['okay', 'okay'],
    'kb': ['keyboard'],
    'k/b': ['keyboard'],
    'kiss': ['keep', 'is', 'simple', 'silly'],
    'kkrh': ['kya', 'kar', 'rahe', 'ho'],
    'lc': ['leaving', 'certificate'],
    'lg': ['lag'],
    'lic': ['like', 'i', 'care'],
    'lk': ['sri', 'lanka'],
    'lmk': ['let', 'me', 'know'],
    'lol': ['laugh', 'out', 'loud'],
    'lolo': ['lots', 'of', 'love'],
    'loa': ['list', 'of', 'acronyms'],
    'luv': ['love'],
    'ly': ['love', 'you'],
    'min': ['minimum'],
    'mins':['minutes'],
    'mnc': ['multi', 'national', 'company'],
    'mo': ['macao'],
    'mob': ['mobile'],
    'ms': ['miss'],
    'mr': ['mister'],
    'msg': ['message'],
    'max': ['maximum'],
    'nhi': ['nahi'],
    'nd': ['and'],
    'ne': ['any'],
    'ne1': ['anyone'],
    'nbd': ['no', 'big', 'deal'],
    'nfw': ['not', 'for', 'work'],
    'nm': ['nothing', 'much'],
    'no.': ['number'],
    'noob': ['newbie'],
    'nowl': ['knowledge'],
    'np': ['no', 'problem'],
    'nt': ['nice', 'try'],
    'nthng': ['nothing'],
    'nxt': ['next'],
    'o4u': ['only', 'for', 'you'],
    'ofc': ['of', 'course'],
    'ok': ['okay'],
    'ootd':['outfit','of','the','day'],
    'op': ['over', 'powered'],
    'omg': ['oh', 'my', 'god'],
    'orly': ['oh', 'really'],
    'otoh': ['on', 'the', 'other', 'hand'],
    'p2p': ['parent', 'to', 'parent'],
    'pcm': ['please', 'call', 'me'],
    'pls':['please'],
    'plz':['please'],
    'plis':['please'],
    'pm': ['personal', 'message'],
    'pr': ['par'],
    'prob': ['probably'],
    'ps': ['post', 'script'],
    'ppl': ['people'],
    'q': ['kyu'],
    'ques': ['question'],
    'qotd': ['question', 'of', 'the', 'day'],
    'qfe': ['question', 'for', 'you'],
    'r': ['are'],
    'r8': ['right'],
    'rha':['raha'],
    'rip': ['rest', 'in', 'peace'],
    'rl': ['real', 'life'],
    'rly': ['railway'],
    'rgr': ['roger'],
    'rofl': ['rolling', 'on', 'the', 'floor', 'laughing'],
    'rut': ['are', 'you', 'there'],
    'ruok': ['are', 'you', 'okay'],
    'sat': ['sorry', 'about', 'that'],
    'sd': ['sweet', 'dreams'],
    'sed': ['sad'],
    'sum': ['some'],
    'some1': ['someone'],
    'stn':['station'],
    'sum1':['someone'],
    'sumthng': ['something'],
    'sq': ['square'],
    'sux': ['sucks'],
    'tc': ['take', 'care'],
    'tal': ['thanks', 'a', 'lot'],
    'tbh': ['to', 'be', 'honest'],
    'tbc': ['to', 'be', 'continued'],
    'tbt': ['throwback', 'thursday'],
    'tel': ['telephone'],
    'tg': ['thank', 'goodness'],
    'thru': ['through'],
    'thnx': ['thanks'],
    'tho':['though'],
    'tot':['thought'],
    'tp': ['time', 'pass'],
    'tq': ['thank', 'you'],
    'ty': ['thank', 'you'],
    'tm': ['trust', 'me'],
    'tyt': ['take', 'your', 'time'],
    'ttyl': ['talk', 'to', 'you', 'later'],
    'u': ['you'],
    'ufo': ['unidentified', 'flying', 'object'],
    'ur': ['your'],
    'urs': ['yours'],
    'uk': ['you', 'know'],
    'ukw': ['you', 'know', 'what'],
    'uw': ["you're", 'welcome'],
    'vry': ['very'],
    'vm': ['voice', 'mail'],
    'vn': ['very', 'nice'],
    'vip': ['very', 'important', 'movie'],
    'vc': ['voice', 'chat'],
    'w3': ['www'],
    'w/end': ['weekend'],
    'wah': ['working', 'at', 'home'],
    'wat': ['what'],
    'wam': ['wait', 'a', 'minute'],
    'wbu': ['what', 'about', 'you'],
    'wc': ['welcome'],
    'wdym': ['what', 'do', 'you', 'mean'],
    'wfh': ['work', 'from', 'home'],
    'whn': ['when'],
    'whr': ['where'],
    'wru': ['where', 'are', 'you'],
    'y': ['why'],
    'yolo': ['you', 'only', 'live', 'once'],
    'yr': ['your'],
    'yw': ["you're", 'welcome'],
    'yt': ['youtube']
}
